// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3IdIB6JR6ZN23YgiRPfGCvDl_oIQErG0',
    appId: '1:906760061694:web:2b8e65f8fa62a77a60dbaf',
    messagingSenderId: '906760061694',
    projectId: 'reciclabenfica',
    authDomain: 'reciclabenfica.firebaseapp.com',
    storageBucket: 'reciclabenfica.firebasestorage.app',
    measurementId: 'G-SCB018N0X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsZNoJe8yVibRQEuJCWIszg5oiq9FRCp0',
    appId: '1:906760061694:android:a74fde13db9b65dc60dbaf',
    messagingSenderId: '906760061694',
    projectId: 'reciclabenfica',
    storageBucket: 'reciclabenfica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQtqdWxj7Io6UdmeopeiOtZWhPr8T00w',
    appId: '1:906760061694:ios:5cf05a4470b9fe6760dbaf',
    messagingSenderId: '906760061694',
    projectId: 'reciclabenfica',
    storageBucket: 'reciclabenfica.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXQtqdWxj7Io6UdmeopeiOtZWhPr8T00w',
    appId: '1:906760061694:ios:5cf05a4470b9fe6760dbaf',
    messagingSenderId: '906760061694',
    projectId: 'reciclabenfica',
    storageBucket: 'reciclabenfica.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3IdIB6JR6ZN23YgiRPfGCvDl_oIQErG0',
    appId: '1:906760061694:web:45d8bfe36c514c1c60dbaf',
    messagingSenderId: '906760061694',
    projectId: 'reciclabenfica',
    authDomain: 'reciclabenfica.firebaseapp.com',
    storageBucket: 'reciclabenfica.firebasestorage.app',
    measurementId: 'G-02JGBBG17H',
  );
}